version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html

    # Install required dependencies
    command: >
      bash -c "
        apt-get update && apt-get install -y \
        libzip-dev \
        && docker-php-ext-install zip \
        && a2enmod rewrite \
        && service apache2 restart \
        && composer install"

    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./laravel:/app
    working_dir: /app