<?php

define('STATUSCODEOK', 200);
define('STATUSCODECREATE', 201);
define('STATUSCODEACCEPTED', 202);
define('STATUSCODEUPDATE', 200);
define('STATUSCODEDELETE', 200);
define('STATUSCODEBADREQUEST', 400);
define('STATUSCODENOTFOUND', 404);
define('STATUSCODENOTAUTHORISED', 401);
define('STATUSCODEUNPROCESSABLE', 422);
